# Generated by Django 5.1.4 on 2024-12-18 15:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('email', 'Email_Required')], default='anyone', max_length=25),
        ),
        migrations.AddField(
            model_name='course',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('draft', 'Draft'), ('soon', 'Coming soon')], default='draft', max_length=25),
        ),
    ]
