# Generated by Django 5.1.4 on 2024-12-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0002_remove_lesson_status_course_access_course_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
