# Generated by Django 5.1.4 on 2024-12-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0003_alter_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='If user does not have access to course, can they see this?'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('draft', 'Draft'), ('soon', 'Coming soon')], default='pub', max_length=25),
        ),
    ]
